### ISSUE TITLE
would like to know if we can do this api/v1/documentation & api/v2/documentation

### ISSUE THREAD

**Issue by odanicola** [DarkaOnLine/SwaggerLume#100]
Hello there,
I would like to know if i have two or more versions of APIs and i want to have two or more swagger ui documentations with routes like this: api/v1/documentation & api/v2/documentation

Can i do that?

**Comment by DarkaOnLine** [comment]
With SwaggerLume no:( But [L5-Swagger](https://github.com/DarkaOnLine/L5-Swagger) supports multiple documentations

**Comment by odanicola** [comment]
Hello thank you for your reply, would you please let me know where the example of multiple documentations using L5-Swagger?

**Comment by DarkaOnLine** [comment]
You can look into config on how to configure multiple docs: https://github.com/DarkaOnLine/L5-Swagger/blob/master/config/l5-swagger.php

**Comment by odanicola** [comment]
should i have two api-docs.json ? or i just need to add the routes?

**Comment by DarkaOnLine** [comment]
2 for sure as these are to different versions of API :)

**Comment by odanicola** [comment]
affirmative, i'll try it... thank you for your reply.

**Comment by testsmith-io** [comment]
> With SwaggerLume no:( But [L5-Swagger](https://github.com/DarkaOnLine/L5-Swagger) supports multiple documentations

But L5-Swagger doesn't work for Lumen projects, right?
