### ISSUE TITLE
How to use swagger.yaml?

### ISSUE THREAD

**Issue by cesarrod11** [DarkaOnLine/SwaggerLume#101]
Hi Guys,

How to use endpoint mapping by a yaml file instead of mapping by annotations in the controllers class?

Example: https://github.com/zircote/swagger-php/blob/master/Examples/petstore.swagger.io/petstore.swagger.io.yaml

**Comment by meysam001** [comment]
I need to know too.

**Comment by DeukhwaJeong** [comment]
Any updates on the issue?

**Comment by DeukhwaJeong** [comment]
@cesarrod11 Thank you for your reply. But could you tell me where I should put my .yaml file? My API is getting bigger so I want to move all of my annotations to a new .yaml file but I don't know where I should create the file and how to read the file. If you know the answer, please let me know! Thanks a lot!
