### ISSUE TITLE
Library should support multiple scan directories

### ISSUE THREAD

**Issue by abbluiz** [DarkaOnLine/SwaggerLume#105]
Related issue: https://github.com/DarkaOnLine/L5-Swagger/issues/63

I want to be able to scan multiple directories. That would be useful in case I am using a custom module with common Open Api definitions as a composer library. Then, I could include `vendor/my-company/common-open-api-specs` in the scan paths, for example.

**Comment by abbluiz-userh** [comment]
Pull Request to make this possible: https://github.com/DarkaOnLine/SwaggerLume/pull/106
