### ISSUE TITLE
Required @OA\Info() not found when running artisann command

### ISSUE THREAD

**Issue by iamNGT** [DarkaOnLine/SwaggerLume#107]
Hi guys ,i have  this error when i run in command line "php artisan swagger-lume:generate" :

In Logger.php line 40:

  Required @OA\Info() not found ,

But i have already initialize the @OA\Info( ) in Controller.php ,some one can help me please??

**Comment by franciscobern** [comment]
This error occurs because annotations to generate doc are missing. In any Controller add. Something similar.

`class ExampleController extends Controller
{
    /**
     * @OA\Info(
     *     title="Test",
     *     version="1.0"
     * ),
     * @OA\Get(
     *     path="/",
     *     @OA\Response(
     *      response="200",
     *      description="Test",
     *    )
     * )
     *
     */
    public function index()
    {
    }
}`
