### ISSUE TITLE
Unable to add headers

### ISSUE THREAD

**Issue by dheersudheer** [DarkaOnLine/SwaggerLume#11]
Hi, 
 I suppose to use basic for my application , Here is my code 
```
basicAuth=  "Basic " + btoa("admin:admin");
swaggerUi.api.clientAuthorizations.add("key", new SwaggerClient.ApiKeyAuthorization("Authorization", basicAuth, "header"));
```
 it is not adding to request headers. Here is the screen shot
![basic auth](https://cloud.githubusercontent.com/assets/19528902/16977592/9f43679c-4e74-11e6-8d82-89a32dc65737.JPG)

**Comment by DarkaOnLine** [comment]
Hi, @dheersudheer 

Additional headers are configured in swagger-lume.php file in the headers section

**Comment by dheersudheer** [comment]
Hi DarkaOnLine,
 I have changed swagger-lume.php as below
   ```
   'headers' => [
        /*
        |--------------------------------------------------------------------------
        | Uncomment to add response headers when swagger is generated
        |--------------------------------------------------------------------------
         */
        /*"view" => [
        'Content-Type' => 'text/plain'
        ],*/
        /*
        |--------------------------------------------------------------------------
        | Uncomment to add request headers when swagger performs requests
        |--------------------------------------------------------------------------
         */
        "request" => [
    'Authorization ' => 'Basic  YWRtaW46YWRtaW4='
    ],
    ],

```
Then still not getting header info .

**Comment by DarkaOnLine** [comment]
First I see the space in `'Authorization '`.
Second, can you check the page source code and see if the header is added in JS?

**Comment by dheersudheer** [comment]
Removed space and checked, I see header in JS in page source code, but still same issue

**Comment by DarkaOnLine** [comment]
Tested myself and for me, everything looks great. Are you getting the same results ?

![image](https://cloud.githubusercontent.com/assets/1171698/16979344/32d1d90a-4e69-11e6-9955-d1d12affa65e.png)


![image](https://cloud.githubusercontent.com/assets/1171698/16979323/153aaa7a-4e69-11e6-908c-c9978eca79f8.png)

**Comment by dheersudheer** [comment]
Did the same thing but not getting same result

**Comment by DarkaOnLine** [comment]
Maybe it is not fresh install and you need to update your config file? Copy
it from vendors directory and make changes.

**Comment by dheersudheer** [comment]
Installed again  but still same issue

**Comment by dheersudheer** [comment]
I have resolved the issue. Actually i added following code in annotations that is the problem.
```
security={
       {
             "type": "basic"
         }
     }
```
Now i just removed it, working fine . thanks for your support @DarkaOnLine

**Comment by DarkaOnLine** [comment]
Glad you found a solution! Happy coding ;)
