### ISSUE TITLE
disable/hide "try it out" button/functionality

### ISSUE THREAD

**Issue by dmontoya-ai** [DarkaOnLine/SwaggerLume#117]
Hello

How do I disable/hide "try it out" button/functionality?

I don't want users to mess with it, They must use other tools like postman or so.

I want Swagger for reference documentation only

Thanks

**Comment by DarkaOnLine** [comment]
You can disable the button with the `tryItOutEnabled: false` in UI loader: https://github.com/DarkaOnLine/SwaggerLume/blob/master/resources/views/index.blade.php#L82

More options in UI docs: https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md

**Comment by dmontoya-ai** [comment]
Hello

Thanks for repy.

I'm having issues with that since every time I refresh the changed tags on the doc (php artisan swagger-lume:publish), this file get rebuild losing my changes: resources/views/vendor/swagger-lume/index.blade.php


The blade file is not refreshed with this other command (php artisan swagger-lume:generate)


About your reply, the tryItOutEnabled: false in UI loader didn't work for me, this method suggested did work instead:  https://stackoverflow.com/questions/55914610/disable-try-it-out-in-swagger


Thanks
