### ISSUE TITLE
it tries to load docs over HTTPS

### ISSUE THREAD

**Issue by testsmith-io** [DarkaOnLine/SwaggerLume#118]
Hello,

Swagger UI tries to load docs over https, https://localhost:8091/docs ... But that doesn't exists. It should be http.

If I change the following line in `SwaggerLumeController.php` it works:

from:
`'urlToDocs' => route('swagger-lume.docs'),`

to:
`'urlToDocs' => route('swagger-lume.docs', null, false),`

Am I missing something? 
I use version 9.x (I also tried 8.x)

The APP_URL is set to `http://localhost:8091`

**Comment by eliseubamaral** [comment]
@testsmith-io have you solved it?
