### ISSUE TITLE
Question about using constants in Swagger annotation

### ISSUE THREAD

**Issue by wjgilmore** [DarkaOnLine/SwaggerLume#12]
Hi,

Your package is fantastic, I'm currently using it to document a Lumen-driven API. Quick question, I'd like to dynamically define the `host` value in `@SWG\Swagger`. The swagger-php documentation mentions this is possible by first defining a constant:

https://github.com/zircote/swagger-php/blob/master/docs/Getting-started.md#using-variables-in-annotations

However to do so the documentation mentions passing along a `constants.php` file. Is there some way to dynamically update annotations using SwaggerLume?

Thank you!

**Comment by DarkaOnLine** [comment]
Hi, @wjgilmore 

In all my API's I have one dedicated PHP file for common annotations.  For Lumen project I am putting it in `app/ApiAnnotations.php` and the content of the file looks like this:

```php

<?php

/**
 * @SWG\Swagger(
 *     basePath="/api/v1",
 *     schemes={"http"},
 *     @SWG\Info(
 *         version="1.0.0",
 *         title="PROJECT TITLE",
 *         @SWG\Contact(
 *             email="your@email.com"
 *         ),
 *     )
 * )
 */

/**
 * @SWG\SecurityScheme(
 *   securityDefinition="api_key",
 *   type="apiKey",
 *   in="query",
 *   name="api_key"
 * )
 */
``` 

My suggestion for you would be put host variable in your environment file. So for example:

- in you `configs/swagger-lume.php` I would add a section like this:

```php
'variables' => [
    'host' => env('API_VARIABLES_HOST', 'http://my-default-host.com'),
 ],
```

- then in your `.env` add the line `API_VARIABLES_HOST=http://my-new-host.com`

- and finally on the top in `app/ApiAnnotations.php`  like documentation says:

```php
define("API_HOST",  config('swagger-lume.variables.host')); 

/**
 * @SWG\Swagger(host=API_HOST)
 */

```

This is my approach.  Hope it will helps you ;)

**Comment by wjgilmore** [comment]
Brilliant thank you so much for clarifying! Makes perfect sense now.

**Comment by bbeniston** [comment]
I tried exactly the same. But when I execute php artisan swagger-lume:generate it results in the following error:

> [ErrorException]
> [Semantical Error] Couldn't find constant API_HOST,

**Comment by DarkaOnLine** [comment]
@bbeniston Can you show yout anotations file ?

**Comment by bbeniston** [comment]
Here it is. It is a .php file.
```
define("API_HOST",  config('swagger-lume.variables.host')); 
 
/**
 * @SWG\Swagger(
 *     schemes={"http","https"},
 *     host=API_HOST,
 *     basePath="/BOP_WEB/src/public/v1",
 *     @SWG\Info(
 *         version="1.0.0",
 *         title="Api Documentation",
 *         description="Api Documentation for the App Developers"
 *     )
 * )
 */
```

**Comment by DarkaOnLine** [comment]
Did you tried replacing `config('swagger-lume.variables.host')` with the string? Did it worked?

**Comment by bbeniston** [comment]
I tried like this `define("API_HOST",  'localhost'); ` It showed the same error.
Do I have to publish any thing else? After this attempt to bring in the constant into the annotation, I tried only this command to get the error: `php artisan swagger-lume:generate`

**Comment by DarkaOnLine** [comment]
Made it a little bit simpler for everyone. See 6a55014c78a6c558ab561a340afba3eac6ec5f38 and run `composer update`

**Comment by bbeniston** [comment]
Works well. Thanks :+1:

**Comment by DarkaOnLine** [comment]
Cheers. Glad could be helpful!
