### ISSUE TITLE
Publishing configuration reset it!

### ISSUE THREAD

**Issue by ollakalla** [DarkaOnLine/SwaggerLume#13]
When i try to publish configuration file by this code
` php artisan swagger-lume:publish-config`
it reset **swagger-lume.php** in **config** folder
i have add this code to header in  **swagger-lume.php**
```
        "request" => [
    'APP_VERSION' => '4.0'
    ],
```
but after run ` php artisan swagger-lume:publish-config`
it become 
```
        /*"request" => [
    'TestMe' => 'testValue'
    ],*/
```

**Comment by DarkaOnLine** [comment]
@ollakalla it's intended behaviour. Published confirm again should overwrite old one.
