### ISSUE TITLE
Support for latest zircote/swagger-php

### ISSUE THREAD

**Issue by halfik** [DarkaOnLine/SwaggerLume#134]
Package does support laravel/lumen-framework ^10.0
But only "zircote/swagger-php": "~2.0 || 3.*"
Problem is you need zircote/swagger-php 4.* to work well with lumen 10. Why we need support for 4.*?

To use laravel doctrine package.  For lumen 10.* we have to use "laravel-doctrine/orm": "^2.0. And this package does use  doctrine/annotations 2.*
So since there is no support for  zircote/swagger-php 4.* there is a conflict. 3.* zicote/swagger-php does require older version of annotations and only 4.* does work with 2.*

**Comment by DarkaOnLine** [comment]
Are you willing to create PR for that?

**Comment by halfik** [comment]
Will try later. If it is some simple change i will make a PR.

**Comment by repirisyan** [comment]
I think this what u need in composer.json
{ "php": "^8.1",
"darkaonline/swagger-lume": "10.*",
"doctrine/annotations": "^1.7",
"laravel/lumen-framework": "^10.0",
"zircote/swagger-php": "^3.3.7" }

and you need to copy the asset from vendor/swagger-api/swagger-ui/dist to public/swagger-ui-assets

i hope that helpfull :)

**Comment by halfik** [comment]
> dor/swagger-api/swagger-ui/dist to public/swagger-ui-assets

It won't work. you need annotation 2+ if u want to use orm 2+.

**Comment by DarkaOnLine** [comment]
https://github.com/DarkaOnLine/SwaggerLume/releases/tag/11.0
