### ISSUE TITLE
Class OpenApi\Generator Not Found - Version Compatibility Issue

### ISSUE THREAD

**Issue by eugene-nuwber** [DarkaOnLine/SwaggerLume#136]
Hi there,

I encountered an error stating that the class OpenApi\Generator was not found. Upon further investigation, it appears that this class was introduced in version 4. However, the current package has a restriction, allowing the use of a maximum version of 3.

Is there any plan to update the package to support version 4 and beyond, or is there an alternative solution for resolving this compatibility issue?

Thank you.

**Comment by nayeemdev** [comment]
+1

**Comment by nayeemdev** [comment]
@eugene-nuwber Were you able to solve it on your end?

**Comment by eugene-nuwber** [comment]
@nayeemdev no, I just tried this package and got this issue.

**Comment by DarkaOnLine** [comment]
https://github.com/DarkaOnLine/SwaggerLume/releases/tag/11.0
