### ISSUE TITLE
SwaggerUI is outdated

### ISSUE THREAD

**Issue by vipaware** [DarkaOnLine/SwaggerLume#16]
Hey, thanks a lot for your package, I'm using it to document my API written in Lumen (doh!).

I was wondering if it makes a big issue to update SwaggerUI to latest version? The current UI used in the package is almost a year old.

Because I need basic auth functionality I actually stopped using built-in UI and only using the package to generate the schema to be inserted in latest UI available on petstore... domain. That's quite sad as I need to instruct all api consumers here on how to actually load the api so they can test endpoints against specific authenticated user. And I want them to be just using swagger ui on our own domain with our schema loaded automatically.
It's not just that, current UI used also contains a lot of other bugs. For example, tooltips on models are broken which makes it very difficult to read tooltips.

Let me know if you have any plans to update the UI.
Thanks!

**Comment by DarkaOnLine** [comment]
You can always publish assets and views by calling a command `swagger-lume:publish` and then replace Swagger UI library and assets. But keep in mind that Swagger UI 2.2.* changed a lot and has build in authentification.

I will update to 2.1.5 definitely in a couple of days.
