### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by dheersudheer** [DarkaOnLine/SwaggerLume#18]
Hi, I'm getting following javascript error. 
![swagger-javasscript error](https://cloud.githubusercontent.com/assets/19528902/20524810/4fb5ad54-b0e2-11e6-89f3-f4e7918d23c8.png)

**Comment by DarkaOnLine** [comment]
Because you accessing it directly :) You ca not do this

**Comment by dheersudheer** [comment]
Then please guide me how to use it

**Comment by DarkaOnLine** [comment]
Please follow README instructions.

But first it looks like you need to configure virtual host.

**Comment by dheersudheer** [comment]
I followed README instructions

**Comment by DarkaOnLine** [comment]
But did you configered lumen and server correctly ?

**Comment by dheersudheer** [comment]
yes

**Comment by DarkaOnLine** [comment]
If you configured virtual host correctly you should be able to access api documentation like this:

`your-virtual-host.dev/api/documentation`

Closing this, because it is not related to the package
