### ISSUE TITLE
SwaggerLume latest version.

### ISSUE THREAD

**Issue by oyepez003** [DarkaOnLine/SwaggerLume#19]
Hi, i am trying to use SwaggerLume in the latest version of Lumen and i got this message.

```
$ php artisan swagger-lume:publish-config

PHP Fatal error:  Call to undefined method Laravel\Lumen\Application::share() in
 C:\xxyy\vendor\darkaonline\swagger-lume\src\ServiceProvider.php on line 46

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined method Laravel\Lumen\Application::share()
```

Next the composer require:
```
...
	"require" : {
		"php" : ">=5.6.4",
		"laravel/lumen-framework" : "5.4.*",
		"vlucas/phpdotenv" : "~2.2",
		"darkaonline/swagger-lume" : "1.*"
	},
...
```

Is there any error on my configuration? or the library does not support the latest version of Lumen.

Thanks and best regards.

**Comment by DarkaOnLine** [comment]
Yes it is because of the new version. I will try to fix it today

**Comment by oyepez003** [comment]
Thanks @DarkaOnLine !!!...

**Comment by DarkaOnLine** [comment]
https://github.com/DarkaOnLine/SwaggerLume/releases/tag/2.0

**Comment by oyepez003** [comment]
Thanks again @DarkaOnLine !!!...
