### ISSUE TITLE
generate_always config option not working

### ISSUE THREAD

**Issue by Hoya** [DarkaOnLine/SwaggerLume#21]
I don't think the generate_always config option is working.
I have mine set to false yet all my swagger docs are available in production.

**Comment by DarkaOnLine** [comment]
Did you checked your `.env` file and SWAGGER_GENERATE_ALWAYS parameter? 
Maby generated json file is included in git ?

**Comment by Hoya** [comment]
This is what my config looks like

> 'generate_always' => env('SWAGGER_GENERATE_ALWAYS', false)

Since I don't have SWAGGER_GENERATE_ALWAYS set in my .env it should default to false right?

**Comment by DarkaOnLine** [comment]
Yes, it should default to false. Did you check your git?

**Comment by Hoya** [comment]
Now that I think about it it does look like I'm pushing the api doc onto git.
Is there a list of files / directories I should add to my .gitignore file?

Also, I'm using AWS Elastic BeanStalk. Will the docs get generated automatically on my staging servers?

**Comment by DarkaOnLine** [comment]
The json documentation file by default is stored in `storage/api-docs` directory. So if you do not want your api documentation to be visible in production you should add this directory to .gitignore.

If you want docs to be generated only in your staging/testing/local environment you should set `SWAGGER_GENERATE_ALWAYS=true` in your `.env` file in each enviroment.

**Comment by Hoya** [comment]
Thanks.

Just one more question. Do I have to add `swagger-lume:generate` to my deploy config or does the docs automatically get generated on deploy?

**Comment by DarkaOnLine** [comment]
Personally, I am using `SWAGGER_GENERATE_ALWAYS=true` only in local/dev environments, that every time when I hit documentation URL it will be regenerated. In staging/production - `php artisan swagger-lume:generate` command in deployment script/config

**Comment by Hoya** [comment]
I think I figured everything out. I have to publish API doc to a secure staging server so that other developers I work with can reference them.
I have separate issue where when I try to access /api/documentation interface via HTTPS swagger tries to read the json doc file via http and failed to redirect. (Can't read from server. It may not have the appropriate access-control-origin settings.) It's a minor issue but I'll post details on a new issue.
Thanks!

**Comment by DarkaOnLine** [comment]
can we close this ?
