### ISSUE TITLE
swagger interface doesn't redirect from http to https

### ISSUE THREAD

**Issue by Hoya** [DarkaOnLine/SwaggerLume#22]
I'm on AWS Elastic BeanStalk with servers behind a load balancer. On lumen I have set it so that all http traffic is forwarded to https traffic.

However when I try to access /api/documentation via HTTPS swagger tried to pull the doc data from HTTP and I get the following error:

`Can't read from server. It may not have the appropriate access-control-origin settings.`

It's a minor issue since I have just manually fix http to https in the input field but a little annoying nonetheless. 

I've tried adding

```
"view" => [
            'Access-Control-Allow-Origin' => env('APP_URL')
        ]
```

but no effect.

Is there a workaround for this?

**Comment by DarkaOnLine** [comment]
try adding this:
```php
'headers' => [
    "request" => [
        'Access-Control-Allow-Origin' => env('APP_URL')
    ]
]
```

and check if you can see correct url in request headers.

**Comment by Hoya** [comment]
Still not working. It looks like it's being blocked from the browser not the server. 

The URL I'm accessing the swagger interface is at `https://staging.{my domain}/api/documentation` but the input field for the documentation shows `http://staging.{my domain}/docs`.

I'm getting a browser error reading 

`Mixed Content: The page at 'https://staging.{my domain}/api/documentation' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://staging.{my domain}/docs'. This request has been blocked; the content must be served over HTTPS.`

**Comment by DarkaOnLine** [comment]
This is related to Swagger UI. Try reading more about this issue: https://github.com/swagger-api/swagger-ui/issues/1670

**Comment by diogolast** [comment]
I'm having the same issue, I updated the swagger-ui but still not working. I looked to the routes.php and find that the secure variable is always coming as false, no matters what I change on my URL.
`'secure' => (new Request)->secure(),`
I am using load balancer on docker, maybe there is something related wih load balancer. @Hoya  Did you find something??

Thanks!!
