### ISSUE TITLE
visit xxx/api/documentation get Target [Illuminate\Contracts\Routing\UrlGenerator] is not instantiable. error

### ISSUE THREAD

**Issue by hemaka** [DarkaOnLine/SwaggerLume#23]
visit xxx/api/documentation get Target [Illuminate\Contracts\Routing\UrlGenerator] is not instantiable. error

after laravel Upgrade 5.3 to 5.4

"php": ">=5.6.4",
"laravel/lumen-framework": "5.4.*",
"darkaonline/swagger-lume": "~2",

**Comment by DarkaOnLine** [comment]
try
`php artisan clear-compiled`
or
`php artisan optimize`

**Comment by hemaka** [comment]
not work.

i remove venddor/darkaonline/swagger-lumen/src/routes.php 51 line url() method

it work

**Comment by ngugijames** [comment]
This is indeed an issue, 
lumen 5.4.* and swaggerLumen 2.0

**Comment by DarkaOnLine** [comment]
Update package and your config file routes section, by adding slash for each route:

```php
'routes' => [
    'api' => '/api/documentation',
    'docs' => '/docs'
],
```
