### ISSUE TITLE
SwaggerUI v3?

### ISSUE THREAD

**Issue by daniel-mcassey-tmsuk** [DarkaOnLine/SwaggerLume#25]
Just wondering if its possible to update to swagger ui v3, as I would like to make use of the Authorization aspect.

**Comment by DarkaOnLine** [comment]
Hi @daniel-mcassey-tmsuk . I am in progress of this update. Hope to release it soon. I am already update [Laravel version](https://github.com/DarkaOnLine/L5-Swagger) so I hope it will not take mush time for the Lumen version.

**Comment by stefanburt** [comment]
Thank you for building this project it's really helped me get up to speed with building APIs.
+1 for UI v3 would be awesome!

**Comment by mglinski** [comment]
Any update on this going live for lumen?

**Comment by DarkaOnLine** [comment]
Finally finished 🎉 🎉 

https://github.com/DarkaOnLine/SwaggerLume/releases/tag/3.0
