### ISSUE TITLE
Unable to generate HTML output

### ISSUE THREAD

**Issue by anil1712** [DarkaOnLine/SwaggerLume#26]
Hi @DarkaOnLine ,
I did the same as per the documentation but I needed HTML output, so that I can share that URL to anyone.

Please suggest me how to convert that JSON response to HTML output.

Thanks.

**Comment by BernardoSilva** [comment]
Hi @anil1712 ,

I am quite new to Laravel/Lumen itself but it might be the case you're accessing the wrong URL?

if you're used the default settings:

* [/docs](https://github.com/DarkaOnLine/SwaggerLume/blob/master/config/swagger-lume.php#L27) is where the swagger annotations that were parsed
* [/api/documentation](https://github.com/DarkaOnLine/SwaggerLume/blob/master/config/swagger-lume.php#L20) is where the Documentation is available in HTML format like you want

Does that help? :)

**Comment by DarkaOnLine** [comment]
Closing this due to no response.
