### ISSUE TITLE
Update README/composer

### ISSUE THREAD

**Issue by jfoliveira** [DarkaOnLine/SwaggerLume#3]
Hi, great package! Thanks a lot for publishing it.

One thing I've noticed about the README:

`composer require "darkaonline/swagger-lume ~1.0"` throws the error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package darkaonline/swagger-lume could not be found in any version, there may be a typo in the package name.
```
Using dev-master it works:
`composer require darkaonline/swagger-lume:dev-master`

Might be worth mentioning that in the README file or create a 1.0 version so the mentioned command line would work.

**Comment by DarkaOnLine** [comment]
Hi,  @jfoliveira
Yes I know that,  just have to check everything one  more time and then I will make a 1.0 release. Thanks!

**Comment by jfoliveira** [comment]
Got it!
Perhaps possible short term solutions are:
1) Create a `0.1.0-alpha-use-at-your-own-risk-dont-blame-me-if-your-life-gets-worse-dude` so it makes clear it's still a non-stable version

2) Use branch aliases: https://getcomposer.org/doc/articles/aliases.md so people could require `1.0.*` and get `dev-master`.

**Comment by DarkaOnLine** [comment]
@jfoliveira I made the release.

`composer require "darkaonline/swagger-lume 1.*"`

 Have fun writing cool API's !!!
