### ISSUE TITLE
SwaggerUIBundle is not defined

### ISSUE THREAD

**Issue by maikelRA** [DarkaOnLine/SwaggerLume#33]
When I try to navigate to api/documentation response SwaggerUIBundle is not defined. In the code, SwaggerUIBundle make reference to swagger-ui/dist/swagger-ui-bundle.js, but I don't know why response SwaggerUIBundle is not defined.

**Comment by DarkaOnLine** [comment]
is swagger-ui-bundle.js loaded or not ? Where do you see this error ?

**Comment by smuthiya** [comment]
I am getting the same error with my Web APIs built using ASPNETCore - 'SwaggerUIBundle' is undefined 
I get this error when i navigate to /swagger to see the UI - but noting loads in browser and I get this error in browser console. However my json endpoint is working i.e. /swagger/v1/swagger.json I get json response back with my API details. But Swagger UI does not work

**Comment by Corneldj** [comment]
I hope this is not too late to post. But I had the same issue and found a solution to it:

1. Check if all your controller methods have [http] tag. If they all do and still doesn't work go to step 2
2. In your configure function ensure that you have app.UseStaticFiles(); If it still doesn't work go to step 3
3. Uninstall and reinstall swagger. If it doesn't work go to step 4 (Core Only)
4. If you are using Core Install Microsoft.AspNetCore.StaticFiles and reference it in your project.

That is as far as I got and mine started working

**Comment by ludonvl** [comment]
I found a solution to this issue. For me, I've needed to copy the /dist directory in "vendor/swagger-api/swagger-ui" inside the /public of my lumen project. I'm not sure about the proper way but it works for me.

Hope this can help someone.

**Comment by Praphulagarwal** [comment]
If you are working with loopback and having this error you can install swagger-ui-dist from
https://www.npmjs.com/package/swagger-ui-dist
this link.

It resolved my problem

**Comment by G-Shriya** [comment]
> I am getting the same error with my Web APIs built using ASPNETCore - 'SwaggerUIBundle' is undefined I get this error when i navigate to /swagger to see the UI - but noting loads in browser and I get this error in browser console. However my json endpoint is working i.e. /swagger/v1/swagger.json I get json response back with my API details. But Swagger UI does not work


Facing the same issue.......Above solutions were of no help

**Comment by jayasundeep** [comment]
I am facing this issue while integrating openapi into SpringBoot application. Any leads would be greater help. TIA

**Comment by aligillaniBD** [comment]
I am facing the same issue with my flask application. It works perfectly fine on my localhost. When I try to run it on k8s environment which have a reverse proxy. It gives me an error in the console that  **SwaggerUIBundle is not defined** and I am not able to see the documentation due to this error.

**Comment by melroyvandenberg** [comment]
Same here.. Exactly like @aligillaniBD explained. What do I need to do!??? What the hack is going on.

**Comment by Codestronomer** [comment]
Same here, Has anyone found a fix yet? I have a Nestjs application. The documentation works on localhost. Not, the same case on my GCP compute instance.

**Comment by bexruzlab** [comment]
I'm looking for solution in node js

**Comment by 26kito** [comment]
I just had this issue but I already solved it. Here is my solution:
1. I downgrade the package swagger-ui-express to 4.3.0
2. In the swagger set up, I added cdn for swagger css and i add customCss to make the style works properly. That's all I'm do
```
// swagger
const swaggerUI = require('swagger-ui-express')
const swaggerDocument = require('./swagger.json')
const swaggerUICss = "https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.3.0/swagger-ui.min.css";

app.use('/api-docs',
    swaggerUI.serve,
    swaggerUI.setup(swaggerDocument, {
        customCss: '.swagger-ui .opblock .opblock-summary-path-description-wrapper { align-items: center; display: flex; flex-wrap: wrap; gap: 0 10px; padding: 0 10px; width: 100%; }',
        customCssUrl: swaggerUICss
    }))
// end of swagger
```

**Comment by marek48medved** [comment]
Hi, I think this issue should be reopen. It is appearing again and again.

**Comment by NyquistJnr** [comment]
@26kito It worked for me, thanks!

**Comment by vishalvoid** [comment]
all of the above things didn't worked for me : this is how i've solved the issue. [medium post ](https://medium.com/@vishalvoid/solving-swaggeruibundle-is-not-defined-error-in-express-with-swagger-cdbc3164fd89)
