### ISSUE TITLE
routes not working

### ISSUE THREAD

**Issue by jmdavid** [DarkaOnLine/SwaggerLume#34]
I installed "darkaonline/swagger-lume": "5.5.*"
The json is generated as well as config file and view but routes are not working:
/api, /docs

**Comment by DarkaOnLine** [comment]
Are you seeing any JS/PHP errors?

**Comment by jmdavid** [comment]
Thanks for answering.

 

Finally, the problem was that files were not copied into /public, I had to manually create a swagger-ui-assets directory and manually copy the files (js and css) from zircote.  The docs don’t say that.

 

Best regards,

 

Jean-Michel David

**Comment by bipycxp** [comment]
@jmdavid I had a similar problem, because a config file(`$app->configure('swagger-lume')`) was added after `Register Container Bindings` section, but need to put it **BEFORE** this section(like in the doc). Hope, it help to fix your problem without copying excess files to `public` folder.

**Comment by jmdavid** [comment]
the line is correctly configured, before the section, just after
$app->withFacades(), but it doesn't copy the required files.

Thanks.
