### ISSUE TITLE
Required @SWG\Info() not found

### ISSUE THREAD

**Issue by amrokhudair** [DarkaOnLine/SwaggerLume#35]
Hi,
Thank you for this package.
I follow all steps and , when I run (php artisan swagger-lume:generate) the terminal return error:
  Required @SWG\Info() not found  
Can you please give me an example how to solve this?!! and where I should put the @SWG\Info() ?

**Comment by DarkaOnLine** [comment]
You can find some information here: https://github.com/DarkaOnLine/SwaggerLume/issues/12

or read swagger documentation
