### ISSUE TITLE
lumen5.5  api/documentation show nothing

### ISSUE THREAD

**Issue by smartyaunt** [DarkaOnLine/SwaggerLume#37]
HI,bro, I use lumen5.5 , this is my code:

/**
 * @SWG\Swagger(
 *     schemes={"http","https"},
 *     host="api.host.com",
 *     basePath="/",
 *     @SWG\Info(
 *         version="1.0.0",
 *         title="This is my website cool API",
 *         description="Api description...",
 *         termsOfService="",
 *         @SWG\Contact(
 *             email="contact@mysite.com"
 *         ),
 *         @SWG\License(
 *             name="Private License",
 *             url="URL to the license"
 *         )
 *     ),
 *     @SWG\ExternalDocumentation(
 *         description="Find out more about my website",
 *         url="http..."
 *     )
 * )
 */

class LessionController extends Controller
{
    /**
     * @SWG\Get(
     *   path="/Controller/LessionController/{customerId}/rate",
     *   summary="List customer rates",
     *   operationId="getCustomerRates",
     *   @SWG\Parameter(
     *     name="customerId",
     *     in="path",
     *     description="Target customer.",
     *     required=true,
     *     type="integer"
     *   ),
     *   @SWG\Parameter(
     *     name="filter",
     *     in="query",
     *     description="Filter results based on query string value.",
     *     required=false,
     *     enum={"active", "expired", "scheduled"},
     *     type="string"
     *   ),
     *   @SWG\Response(response=200, description="successful operation"),
     *   @SWG\Response(response=406, description="not acceptable"),
     *   @SWG\Response(response=500, description="internal server error")
     * )
     *
     */
    public function index() {
        return [
            'apple',
            'orgran',
            'banana',
        ];
    }
}

I haved run command  "php artisan swagger-lume:generate”  it no error output
but http://xxxx/api/documentation show nothing

**Comment by dimmduh** [comment]
Same issue :(

**Comment by dimmduh** [comment]
Copyed some files from _vendor\swagger-api\swagger-ui\dist_ to _public\swagger-ui-assets_
I think this issue related to #34

**Comment by DarkaOnLine** [comment]
can you see the content of:

http://your-domain.dev/swagger-ui-assets/swagger-ui.css
http://your-domain.dev/swagger-ui-assets/swagger-ui-bundle.js
http://your-domain.dev/swagger-ui-assets/swagger-ui-standalone-preset.js

If no, what errors are you getting?

**Comment by DarkaOnLine** [comment]
Also, see this #28, if you are using build in php server: https://github.com/DarkaOnLine/SwaggerLume/issues/28

**Comment by DarkaOnLine** [comment]
You do not have to copy these assets if your server is configured correctly. Assets controller should serve you all assets without copying them to public folder.
