### ISSUE TITLE
/api/documentation - Content-Type

### ISSUE THREAD

**Issue by cocochepeau** [DarkaOnLine/SwaggerLume#39]
Hi,

The `/api/documentation` route does not send any `Content-Type: text/html` header. Thus, some web browser won't display the page as HTML but plain text.

Forcing the header (here https://github.com/DarkaOnLine/SwaggerLume/blob/master/src/Http/Controllers/SwaggerLumeController.php#L59) should fix the issue.

Do you want me to send a PR?

Thanks.

**Comment by DarkaOnLine** [comment]
@cocochepeau, PR would be great. Thanks!

**Comment by ishan123456789** [comment]
Still getting result as plain text:

![swagger](https://user-images.githubusercontent.com/23247168/37732999-aca55354-2d6c-11e8-8629-98c8226ac772.PNG)
