### ISSUE TITLE
How to change swagger version from 2.0 to 3.0 ?

### ISSUE THREAD

**Issue by nirmalgoswami** [DarkaOnLine/SwaggerLume#41]
Hello,

First of all thanks for great work on `SwaggerLume`

I am trying to use `type='object'` in `@SWG\Parameter(` and found that   `type='object'` in not working in swagger `2.0` so i want to change from `2.0` to `3.0`. 

i am trying to implement following definition

```
* @SWG\Parameter(
 *   name="body",
 *   in="body",
 *   description="cart data",
 *   required=true,
 *   @SWG\Schema(
 *       type="object",
 *       @SWG\Property(
 *         property="cart",
 *         type="array",
 *         @SWG\Items(
 *           type="object",
 *           @SWG\Property(property="product_id", type="integer"),
 *           @SWG\Property(property="amount", type="integer")
 *         )
 *       )
 *     )
 *   )
 * ),
```

what are the steps to change swagger version ? i am using `2.0`

**Comment by DarkaOnLine** [comment]
Swagger 3.0, a.k.a `OpenApi Spec` is not yet supported in SwaggerLume. 
I am planning to implement this in a couple of days.

Keep in mind if you will migrate to OpenAPI you will have to rewrite all your annotation. Here is example of OpenApi pet store: https://github.com/zircote/swagger-php/tree/3.x/Examples/petstore-3.0
