### ISSUE TITLE
php artisan swagger-lume:generate "No operations defined in spec!"

### ISSUE THREAD

**Issue by amjad-eremnews** [DarkaOnLine/SwaggerLume#43]
When i run the following command
`php artisan swagger-lume:generate
`
and i see "No operations defined in spec!" on http://localhost/api/v1/documentation

Here is my base controller

```
namespace App\Http\Controllers;

use Laravel\Lumen\Routing\Controller as BaseController;
use Illuminate\Http\Request;

class Controller extends BaseController
{}

/**
 * @SWG\Swagger(
 *     basePath=L5_SWAGGER_CONST_BASE_PATH,
 *     schemes={"http", "https"},
 *     host=L5_SWAGGER_CONST_HOST,
 *     @SWG\Info(
 *         version="1.0.0",
 *         title="L5 Swagger API",
 *         @SWG\Contact(
 *             email="webmaster@localhost.com"
 *         ),
 *     )
 * )
 */
/**
 * @SWG\Tag(
 *     name="users",
 *     description="Operations about user",
 *     @SWG\ExternalDocumentation(
 *         description="Find out more about store",
 *         url="http://swagger.io"
 *     )
 * )
 */
/**
 * @SWG\SecurityScheme(
 *   securityDefinition="api_key",
 *   type="apiKey",
 *   in="query",
 *   name="api_key"
 * )
 */
/**
 * @SWG\SecurityScheme(
 *   securityDefinition="X-Api-Token",
 *   type="apiKey",
 *   in="header",
 *   name="X-Api-Token"
 * )
 */
```

This is my user controller login function 

```
/**
     * Handle a login request to the application.
     *
     * @SWG\Post(path="/login",
     *   tags={"User actions"},
     *   summary="Perform user sign in",
     *   description="login user using request data",
     *   produces={"application/json"},
     *   consumes={"application/json"},
     *     @SWG\Parameter(
     *     in="body",
     *     name="login user",
     *     description="JSON Object which login user",
     *     required=true,
     *     @SWG\Schema(
     *         type="object",
     *         @SWG\Property(property="email", type="string", example="user@mail.com"),
     *         @SWG\Property(property="password", type="string", example="password"),
     *     )
     *   ),
     *   @SWG\Response(response="200", description="Return token or error message")
     * )
     *
     * @param Request $request
     *
     * @return Response
     */
public function login(Request $request){}
```

**Comment by DarkaOnLine** [comment]
Can you access your generated`.json` file?

`http://localhost/api/v1/docs`

**Comment by amjad-eremnews** [comment]
No, getting


```
(1/1) NotFoundHttpException
--
in RoutesRequests.php (line 226)
```

**Comment by amjad-eremnews** [comment]
Here is my swagger-lume.php
```

`    'routes' => [
        /*
        |--------------------------------------------------------------------------
        | Route for accessing api documentation interface
        |--------------------------------------------------------------------------
         */
        'api' => '/api/v1/documentation',

        /*
        |--------------------------------------------------------------------------
        | Route for accessing parsed swagger annotations.
        |--------------------------------------------------------------------------
         */
        'docs' => '/docs',`
...........................................

    /*
    |--------------------------------------------------------------------------
    | Uncomment to add constants which can be used in anotations
    |--------------------------------------------------------------------------
     */
    'constants' => [
        // 'SWAGGER_LUME_CONST_HOST' => env('SWAGGER_LUME_CONST_HOST', 'http://my-default-host.com'),
        'L5_SWAGGER_CONST_HOST'      => env('L5_SWAGGER_CONST_HOST', 'http://localhost'),
        'L5_SWAGGER_CONST_BASE_PATH' => env('L5_SWAGGER_BASE_PATH', '/api/v1'),
    ],



```

**Comment by DarkaOnLine** [comment]
Is generated json file exist in your storage path?

**Comment by amjad-eremnews** [comment]
yes

**Comment by DarkaOnLine** [comment]
So the package is working correctly, but something is overriding `docs` route.

Run `php artisan route:list` and investigate.

**Comment by amjad-eremnews** [comment]
for lumen this command gives me following error

` There are no commands defined in the "route" namespace. `

**Comment by DarkaOnLine** [comment]
Try this package https://github.com/appzcoder/lumen-route-list

**Comment by amjad-eremnews** [comment]
now i get 

`php artisan route:list
+--------+-------------------------------------+------------------------------+---------------------------------------------------------+----------------+----------------------------------------------------------------------+
| Verb   | Path                                | NamedRoute                   | Controller                                              | Action         | Middleware                                                           |
+--------+-------------------------------------+------------------------------+---------------------------------------------------------+----------------+----------------------------------------------------------------------+
| GET    | /docs                               | swagger-lume.docs            | SwaggerLume\Http\Controllers\SwaggerLumeController      | docs           |                                                                      |
| GET    | /api/v1/documentation               | swagger-lume.api             | SwaggerLume\Http\Controllers\SwaggerLumeController      | api            |                                                                      |
| GET    | /swagger-ui-assets/{asset}          | swagger-lume.asset           | SwaggerLume\Http\Controllers\SwaggerLumeAssetController | index          |                                                                      |
| GET    | /api/oauth2-callback                | swagger-lume.oauth2_callback | SwaggerLume\Http\Controllers\SwaggerLumeController      | oauth2Callback |                                                                      |
| GET    | /api/v1                             |                              | None                                                    | Closure        |                                                                      |
| POST   | /api/v1/login                       |                              | App\Http\Controllers\UserController                     | login          |                                                                      |
| POST   | /api/v1/user/{email}/password/send  |                              | App\Http\Controllers\UserController                     | sendEmail      |                                                                      |
| POST   | /api/v1/user/password/reset/{token} | password.reset               | App\Http\Controllers\UserController                     | reset          |   `

**Comment by DarkaOnLine** [comment]
Hmm, it's a fresh installation.  It should work. I am out of options here.

**Comment by amjad-eremnews** [comment]
Fixed by changing  'docs'  param in config/swagger-lume.php

Before change:
```
/*
        |--------------------------------------------------------------------------
        | Route for accessing parsed swagger annotations.
        |--------------------------------------------------------------------------
         */
        'docs' => '/docs',

```

After change:

```
/*
        |--------------------------------------------------------------------------
        | Route for accessing parsed swagger annotations.
        |--------------------------------------------------------------------------
         */
        'docs' => '/api/v1/docs',
```
