### ISSUE TITLE
How to create a view of the JSON generated ?

### ISSUE THREAD

**Issue by ishan123456789** [DarkaOnLine/SwaggerLume#44]
After a lot of searching I was able to get a JSON which when I put in the online swagger editor produce a UI but how to automatically generate a UI component as when I define a route for the swaggers index.php like this
`
$app->get('/api', function ()  {
    return view('vendor.swagger-lume.index');
});`
file I get a lot errors like this 

```
(2/2) ErrorExceptionUndefined variable: urlToDocs (View: E:\xampp\htdocs\api\resources\views\vendor\swagger-lume\index.blade.php)
--
```

I know this is not the exact way but the lack of complete documentation is giving a very hard time.So can you please explain this part how to render the `vendor/swagger-lume/index.php`

Here is what happens if I try to give the path referred in the `config/swagger-lume.php` file.

![swagger-bug](https://user-images.githubusercontent.com/23247168/37789521-251a1a28-2e2a-11e8-8033-1ef40ceadd9f.PNG)

And of I visit api/documentation here is the error I get

![swagger-doc-error](https://user-images.githubusercontent.com/23247168/37790559-ec4aec88-2e2c-11e8-8fcc-5aca38c7546e.PNG)

**Comment by DarkaOnLine** [comment]
It looks like you update SwaggerLume, but not your config file.

Please copy and paste https://github.com/DarkaOnLine/SwaggerLume/blob/master/config/swagger-lume.php to your config.

**Comment by ishan123456789** [comment]
I fixed it using another issue by running 
`php -S localhost:8000 public/index.php`
I don't know what the cause might be but it started running after this.
As earlier I was running through `php -S localhost:8000 -t public`

**Comment by DarkaOnLine** [comment]
Oh yes, it is php build in servers bug. Glad you managed to fix this.
