### ISSUE TITLE
How to view swagger doc using command

### ISSUE THREAD

**Issue by 1nfinite** [DarkaOnLine/SwaggerLume#45]
Currently I am copy pasting the json to swagger editor to display it.

I am expecting something like `php artisan swagger-lume:view` to view the swagger doc.
Is this function available? or i just miss it cause i don't see any in documentation.

**Comment by DarkaOnLine** [comment]
If you did not change anything in config file, you can view your documentation by cvisiting

http://you-project-url.dev/api/documentation

Or you can change it, by publishing config and changing this: https://github.com/DarkaOnLine/SwaggerLume/blob/master/config/swagger-lume.php#L20
