### ISSUE TITLE
Swagger UI set to HTTPS by default

### ISSUE THREAD

**Issue by Al3xR0** [DarkaOnLine/SwaggerLume#46]
Fetch errorFailed to fetch https://DOMAIN/docs
Fetch errorPossible cross-origin (CORS) issue? The URL origin (https://DOMAIN) does not match the page (http://DOMAIN). Check the server returns the correct 'Access-Control-Allow-*' headers.

I already added ```schemes={"http"},```, but it still opens as https as default. What can I do? I have lumen 5.6.

**Comment by DarkaOnLine** [comment]
What is your APP_URL defined in `.env` file?

**Comment by Al3xR0** [comment]
@DarkaOnLine don't have it in the ```.env``` file. I added it like this ```APP_URL=http://DOMAIN``` and still opens with https.

**Comment by Al3xR0** [comment]
@DarkaOnLine great, it works now 👍

**Comment by vitanivanov** [comment]
@DarkaOnLine I'm using lumen 5.5.2 and it is still reproducible.

**Comment by abdulla-allaith** [comment]
This PR solves the issue for me https://github.com/DarkaOnLine/SwaggerLume/pull/62

**Comment by ivann1** [comment]
@DarkaOnLine Error is still reproducible, since you only fixed the asset part of the HTTPS problem. The docs part still remains
