### ISSUE TITLE
Please provide to work with openapi 3 lumen 5.5

### ISSUE THREAD

**Issue by prasadsilicus** [DarkaOnLine/SwaggerLume#49]
We have successfully integrated package (composer require "darkaonline/swagger-lume:5.5.*" ) with lumen 5.5 and swagger document generated successfully..

Now I want to integrate Open API 3.. please provide detail step by step to do it...

**Comment by DarkaOnLine** [comment]
Please read: https://github.com/DarkaOnLine/SwaggerLume#using-openapi-30-specification

If you need more info, please ask exact questions.

**Comment by prasadsilicus** [comment]
lumen 5.5 will work with this package composer require zircote/swagger-php:3.*

**Comment by DarkaOnLine** [comment]
If you want to use OpenApi you need 5.6.* version of SwaggerLume `composer require "darkaonline/swagger-lume:5.6.*"`

and then: `composer require "zircote/swagger-php:3.*"`
