### ISSUE TITLE
 php artisan swagger-lume:generate command gives error when upgraded to 5.6

### ISSUE THREAD

**Issue by amjad-eremnews** [DarkaOnLine/SwaggerLume#50]
` php artisan swagger-lume:generate` command gives error when upgraded to 5.6

```
Regenerating docs

In Logger.php line 38:
                                  
  Required @OAS\Info() not found
```

**Comment by DarkaOnLine** [comment]
You MUST provide Info annotation. Please read OpenApi documentation! https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#infoObject

**Comment by amjad-eremnews** [comment]
But i don't want to use OpenApi Spec 3.0, and want to stay with 2.0

**Comment by DarkaOnLine** [comment]
What version of swagger-php is installed? `composer info | grep swagger-php`

**Comment by amjad-eremnews** [comment]
from my composer.json file
`"darkaonline/swagger-lume": "^5.5"`
I removed vendor directory, and then run command` composer update`. 
and new version of swagger-lume installed swagger-php 3.0 by default. although it is not in my composer.json file, but required by your composer.json from new version.

**Comment by DarkaOnLine** [comment]
You are right. Releasing hotfix now. Thanks!
