### ISSUE TITLE
error in the swagger lume

### ISSUE THREAD

**Issue by idan003** [DarkaOnLine/SwaggerLume#53]
Hello,

`[Tue Jul 24 17:44:39 2018] ::1:57133 [200]: /api/documentation
[Tue Jul 24 17:44:39 2018] ::1:57136 [404]: /swagger-ui-assets/swagger-ui.css?v=5a547f5645edb0cf963a796f34eed06b - No such file or directory
[Tue Jul 24 17:44:39 2018] ::1:57137 [404]: /swagger-ui-assets/swagger-ui-bundle.js?v=3d68d211488eba1178503308e70caabc - No such file or directory
[Tue Jul 24 17:44:39 2018] ::1:57138 [404]: /swagger-ui-assets/swagger-ui-standalone-preset.js?v=c30a2a12a47f2c4ca81b3cb7076a31bf - No such file or directory
[Tue Jul 24 17:44:39 2018] ::1:57139 [404]: /swagger-ui-assets/swagger-ui-standalone-preset.js?v=c30a2a12a47f2c4ca81b3cb7076a31bf - No such file or directory
`
when i try to access to api/documentation
i get in the console this error i sent

i use Lumen (5.6.4) (Laravel Components 5.6.*)

**Comment by normeno** [comment]
Try copying vendor\swagger-api\swagger-ui\dist to public\swagger-ui-assets.

**Comment by leonachman** [comment]
Had the same issue today on Lumen 5.7.
Copying vendor\swagger-api\swagger-ui\dist to public\swagger-ui-assets worked for me.

**Comment by sudkumar** [comment]
Same thing here. Lumen has some issues with loading assets from vendor due to it fast router (I guess.) What I did was, added a `post-install-cmd` script in the `composer.json` to copy the folder in install.

```json
{
    "scripts": {
        "post-install-cmd": [
            "cp -a vendor/swagger-api/swagger-ui/dist public/swagger-ui-assets"
        ],
    }
}
```

**Comment by Carsak** [comment]
Only manually copying assets to public folder helped
