### ISSUE TITLE
zircote package updation for open api

### ISSUE THREAD

**Issue by themifycloud** [DarkaOnLine/SwaggerLume#55]
Hello Dear,
Zircote package has been updated for open api annotations. Please update swagger lume as well. I am getting error that swagger/scan function does not exit. 
Thanks

**Comment by DarkaOnLine** [comment]
It was implemented #54 couple of days ago

**Comment by tukataka** [comment]
@DarkaOnLine Hi!
Right now i'm getting this error
`[2018-08-03 14:30:42] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function OpenApi\scan() in /var/www/vendor/darkaonline/swagger-lume/src/Generator.php:25`
As i understand it cause you didn't add OpenApi to requirements in composer.json.
Can you recheck it pls ?

**Comment by DarkaOnLine** [comment]
@tukataka when OpenApi in Swagger-PHP will be stable I will bump the version of the package and only support OpenApi. But for now, because swagger-php openApi is still not stable, I will leave as it is.

**Comment by golden987** [comment]
> 
> 
> @DarkaOnLine Hi!
> Right now i'm getting this error
> `[2018-08-03 14:30:42] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function OpenApi\scan() in /var/www/vendor/darkaonline/swagger-lume/src/Generator.php:25`
> I found, that i need to choose version of zircote/swagger-php in my composer.json.
> Don't you think, that need make two version of library with different versions of zircote/swagger-php ?

how can i choose the version... i have that problem but i can't find a solution, please help me :D

**Comment by DarkaOnLine** [comment]
just run this command: `composer require 'zircote/swagger-php:2.*'`

**Comment by firhansyah** [comment]
why when I execute the command "composer require 'zircote / swagger-php: 2. *" error appears "Could not parse version constraint 2. *': Invalid version string" 2. * '"?

**Comment by DarkaOnLine** [comment]
You have a lot of spaces in your command and version

**Comment by aplikasih** [comment]
composer require zircote/swagger-php:2.*

work on my composer
