### ISSUE TITLE
SwaggerLume for laravel/lumen-framework 5.7.*

### ISSUE THREAD

**Issue by if08017** [DarkaOnLine/SwaggerLume#57]
How to install SwaggerLume for Lumen-framework 5.7.*

i got `Required @OA\Info() not found` when i run `php artisan swagger-lume:generate`

best

**Comment by pacoogle** [comment]
Hi dear, this nomenclature is deprecated. You must use:
`/**
 * @SWG\Swagger(
 *     schemes={"http","https"},
 *     host="test.com",
 *     basePath="/",
 *     @SWG\Info(
 *         version="1.0.0",
 *         title="Test API",
 *         description="API signature description",
 *     ),
 *     @SWG\ExternalDocumentation(
 *         description="Find out more about my website",
 *         url="http"
 *     )
 * )
 */`

**Comment by xoxefdp** [comment]
Actually what worked for me for the 5.7.* of Lumen is

`
 /**
 * @OA\Info(title="Proxmox Lumen Restful", version="1.0.0")
 */

/**
 * @OA\Get(
 *     path="/api/resource.json",
 *     @OA\Response(response="200", description="An example resource")
 * )
 */
`

The @SWG\Swagger works fine for OAS 2.0 specification. Check on the [installation compatibility table](https://github.com/DarkaOnLine/SwaggerLume#installation)

**Comment by DarkaOnLine** [comment]
Be default SwaggerLume will use OpenApi annotations like `@OA\` if you want to use older version `@SWG\` you need to `composer require 'zircote/swagger-php:2.*'`
