### ISSUE TITLE
[Lumen 5.7] Class 'SwaggerLume\ServiceProvider' not found 

### ISSUE THREAD

**Issue by maglor** [DarkaOnLine/SwaggerLume#58]
I have an error while installing SwaggerLume to Limen 5.7
bootstrap/app.php:
```
$app->configure('swagger-lume');
$app->register(\SwaggerLume\ServiceProvider::class);
```

**Comment by DarkaOnLine** [comment]
What kind of error :)

**Comment by furkankadioglu** [comment]
Command => **php artisan swagger-lume:generate**
```
Regenerating docs
In Logger.php line 39:
  Required @OA\Info() not found
```

**Comment by AmrAlmagic** [comment]
@furkankadioglu  Are you solve this issue?

**Comment by DarkaOnLine** [comment]
@OA\Info() is a required annotation. Please read OpenApi documentation

**Comment by Myusuf060696** [comment]
i got this error 
` Call to undefined method Laravel\Lumen\Application::group()`

after add` $app->register(\SwaggerLume\ServiceProvider::class); ` at bootstrap/app.php

**Comment by brunofarina** [comment]
@furkankadioglu You have to use **@OA\Info** like that:

`@OA\Info( title="Auth Controller", version="test") `

Like @DarkaOnLine , you must read OpenApi documentation for understand how and where to put these annotations on your code.

**Comment by AmirHoseinBahrami** [comment]
install again :
composer require "darkaonline/swagger-lume:8.*"
