### ISSUE TITLE
API_KEY_VAR no longer used?

### ISSUE THREAD

**Issue by jfoliveira** [DarkaOnLine/SwaggerLume#6]
I've just upgraded to 1.0.1 and the config setting
```
'key_var' => env('API_KEY_VAR', 'token'),
```
is no longer being used.

I found [this commit](https://github.com/DarkaOnLine/SwaggerLume/commit/319444f44419a208a86885e98903f0ae880d6df5#diff-e09897fbdd2918deee752b67af496219L65) that removed the references to `apiKeyVar` from `index.blade.php`.

Is there any other way to set a custom `api_key` var?

**Comment by DarkaOnLine** [comment]
Sorry for this bug :( Don't know I missed this :( Releasing 1.0.2

**Comment by jfoliveira** [comment]
Awesome! Thanks!
