### ISSUE TITLE
question: handle multiple API versions

### ISSUE THREAD

**Issue by nsn0x01** [DarkaOnLine/SwaggerLume#60]
Hi,

How could I handle multiple definitions for my API versions like v1, v2, v3... ?

I'm using different namespaces inside Lumen for each API version, the generation command try to scan everything.. is it not possible generate the definitions based on a folder? 

something like:
php artisan swagger-lume:generate ApiV1   
php artisan swagger-lume:generate ApiV2

**Comment by testsmith-io** [comment]
if we can specify a configuration file, then supporting multiple api-version would also be possible. Any change to integrate this?

**Comment by chippythomas18** [comment]
did you solved it @nsn0x01 @DarkaOnLine
