### ISSUE TITLE
[Lumen 5.7] How to install SwaggerLume for Lumen framework 5.7.*

### ISSUE THREAD

**Issue by zKenCylz** [DarkaOnLine/SwaggerLume#61]
I installed by command: composer require "darkaonline / swagger-lume: 5.7. *"
but it does not seem to support lumen version 5.7
Please guide me how to install Swagger for Lumen 5.7

**Comment by DarkaOnLine** [comment]
What errors you are getting?

**Comment by rasyid46** [comment]
hai i have same problem with lumen 5.7 
run http://localhost:8000/api/documentation
this log message ?
 /swagger-ui-assets/swagger-ui.css?v=91aaaabdd10a37ee7c4c446c597c3c34 - No such file or directory

**Comment by aluisiora** [comment]
> I installed by command: composer require "darkaonline / swagger-lume: 5.7. *"
> but it does not seem to support lumen version 5.7
> Please guide me how to install Swagger for Lumen 5.7

I was able to use Swagger Lume 5.6.* with Lumen 5.7 since there is no swagger-lume 5.7.


> hai i have same problem with lumen 5.7
> run http://localhost:8000/api/documentation
> this log message ?
> /swagger-ui-assets/swagger-ui.css?v=91aaaabdd10a37ee7c4c446c597c3c34 - No such file or directory

I was getting this error with the php server, if you are using that, try running the server like this:
```bash
php -S localhost:8000 public/index.php
```

Note that there is no `-t public`. Hope that helps.

**Comment by darurats** [comment]
Anyone can help me? I got this error 
`Unexpected field "basePath" for @OA\OpenApi(), expecting "openapi", "info", "servers", "paths", "components", "security", "tags", "externalDocs", "x" in`

Thanks in advance.

**Comment by DarkaOnLine** [comment]
In OpenApi `basePath` is no longer exists in. Please read documetation:

`In OpenAPI 3.0, you use the servers array to specify one or more base URLs for your API. servers replaces the host, basePath and schemes keywords used in OpenAPI 2.0. Each server has an url and an optional Markdown-formatted description.` - https://swagger.io/docs/specification/api-host-and-base-path/
