### ISSUE TITLE
[Feature Request] Hide and Prefill Client_id, Client_Secret and Client credentials location

### ISSUE THREAD

**Issue by ThaDaVos** [DarkaOnLine/SwaggerLume#66]
![image](https://user-images.githubusercontent.com/5251028/53955636-d4931280-40d9-11e9-8d63-3e2a103bdd9a.png)
I would love to be-able to hide the shown fields and pre-fill them with the client_id and client_secret defined in my .env file and also default the client credentials location to body.
Is this possible?

**Comment by hero3616** [comment]
Me too :)
