### ISSUE TITLE
No UI

### ISSUE THREAD

**Issue by shindakioku** [DarkaOnLine/SwaggerLume#69]
![image](https://user-images.githubusercontent.com/28839051/55687248-9e181400-5973-11e9-854b-62e6013525c2.png)
I didn't change config.

`http://localhost:8080/docs` - is works.

**Comment by gabrielresende06** [comment]
It's missing the swagger UI assets.
Did you add $app->configure('swagger-lume'); before the Register Container Bindings (after $app->withEloquent();) in the bootstrap/app.php ?

You can also run these commands, it's should work as well.

mkdir public/swagger-ui-assets
cp vendor/swagger-api/swagger-ui/dist/* public/swagger-ui-assets

**Comment by shindakioku** [comment]
@gabrielresende06 thanks!
(I did `mkdir` and `cp`)
