### ISSUE TITLE
Issue when auth_token config had value

### ISSUE THREAD

**Issue by tranxuanhao2001** [DarkaOnLine/SwaggerLume#7]
Hi guys, 

1- REPORT ERROR:

> I use your library and apprance issue:

> 'auth_token' config default value is 'false'. But I want to default value isn't false => Error javascript in index.blade.php

> - File: /resources/views/vender/swagger-lume/index.blade.php
> - Line: window.swaggerUi.api.clientAuthorizations.add("{{$apiKeyVar}}", apiKeyAuth);
> - Description error: documentation:86 Uncaught TypeError: Cannot read property 'clientAuthorizations' of null
> - Because: window.swaggerUi don't loaded
> - Fix: Move window.swaggerUi.load(); before function addApiKeyAuthorization(). Cause: first window.swaggerUi, second call function addApiKeyAuthorization()

2- FEEDBACK FEATURE
I use oauth2, normal key will add prefix (BEAERER, BASIC....)

Update: 
- Add 'key_prefix' in file config
- Get 'key_prefix' in file route to send view
- Add 'key_prefix' before key in file index.blade.php

`if(key && key.trim() != "") {
          var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization("{{$apiKeyVar}}",{{$apiPrefixKeyVar}} + key, "{{$apiKeyInject}}");
          window.swaggerUi.api.clientAuthorizations.add("{{$apiKeyVar}}", apiKeyAuth);
}`

Thanks

**Comment by DarkaOnLine** [comment]
Hi, @tranxuanhao2001 

Thanks for your feedback.

Maybe you can make a PR for this ?

**Comment by tranxuanhao2001** [comment]
Sorry, I can't push code to new branch 

remote: Permission to DarkaOnLine/SwaggerLume.git denied to tranxuanhao2001.
fatal: unable to access 'https://github.com/DarkaOnLine/SwaggerLume.git/': The requested URL returned error: 403

**Comment by DarkaOnLine** [comment]
You have to fork this repository. Make changes and from your fork, make pull request.

Some articles about this:

https://help.github.com/articles/fork-a-repo/
https://guides.github.com/activities/forking/
https://help.github.com/articles/creating-a-pull-request/
