### ISSUE TITLE
Issue with installation into empty lumen project

### ISSUE THREAD

**Issue by Swift-Jr** [DarkaOnLine/SwaggerLume#71]
I'm working with Lumen 5.8.*

I've simply created a new empty lumen project, and edit routes/web.php to include this:

`/**
 * @OA\Info(
 *     description="Sample app",
 *     version="1.0.0",
 * )
 */

 /**
   * @OA\Get(path="sample/{param}",
   *   summary="Sample API endpoint",
   *   description="A description",
   *   @OA\Parameter(
   *     name="param",
   *     in="path",
   *     description="A param",
   *     required=true,
   *     @OA\Schema(
   *         type="string"
   *     )
   *   ),
   *   @OA\Response(response=200, description="OK"),
   *   @OA\Response(response=404, description="Failed")
   * )
   *
   */
$router->get('sample/{param:[A-Za-z]+}', function ($param) use ($router) {
        return $router->app->version();
    });

?>

I followed the install with no changes, but running php artisan swagger-lume:generate gives me 

In Logger.php line 39:

  Required @OA\Info() not found

Any ideas?

**Comment by DarkaOnLine** [comment]
As it says OA\Info not found. So maybe you are missing something.

**Comment by Swift-Jr** [comment]
I presume it's setup to automatically read from routes/web.php?

Or do we need to manually update the config?

Thanks :)

**Comment by DarkaOnLine** [comment]
It is not. It reads app folder.

**Comment by Swift-Jr** [comment]
Closing this then - updating line 75 of swagger-lume.php to 
`        'annotations' => base_path('routes'),`

solved it for me :)
