### ISSUE TITLE
swagger_lume_asset

### ISSUE THREAD

**Issue by leonardyrj** [DarkaOnLine/SwaggerLume#72]
How do I return https in the url of css and js.

I have already changed the APP_URL variable to HTTPS and it still does not work.

File: sagger-lume/index.blade.php

` <link rel="stylesheet" type="text/css" href="{{ swagger_lume_asset('swagger-ui.css') }}" >
    <link rel="icon" type="image/png" href="{{ swagger_lume_asset('favicon-32x32.png') }}" sizes="32x32" />
    <link rel="icon" type="image/png" href="{{ swagger_lume_asset('favicon-16x16.png') }}" sizes="16x16" />`

**Comment by arnacmj** [comment]
@leonardyrj did you fix this issue, assets is not loading in https scheme?

**Comment by MatKonstantin** [comment]
The problem is not swagger-lumen. It uses the standard route() function of the lumen/laravel. You can check your lumen settings and return some of your routes. For example
`$router->get('/test_route', ['as' => 'test', function () {
        return route('test');
}]);`

**Comment by lolo3129** [comment]
# ref https://cylab.be/blog/122/using-https-over-a-reverse-proxy-in-laravel
1. add this in your boot Provider (and configure .env app_url accordingly


        if ($this->app->environment('production') && !empty(config('app.url'))) {
            $schema = explode(':', config('app.url'))[0];
            URL::forceScheme($schema);
        }

2. you need to change swagger_lume_asset helper by removing last route parameter (app('request')->secure()
