### ISSUE TITLE
cannot make array request

### ISSUE THREAD

**Issue by powehuda** [DarkaOnLine/SwaggerLume#78]
i try write code like this :

 /**
    * @SWG\Tag(
    *   name="Project Plan",
    *   description="Fitur api Project Plan"
    * )
    * @SWG\Post(
    *   path="/project_plan/simpan",
    *   summary="simpan data Project Plan",
    *   tags={"Project Plan"},
    *   @SWG\Parameter(
    *     name="token",
    *     in="header",
    *     description="Token untuk login",
    *     required=true,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="lop_name",
    *     in="formData",
    *     description="Lop Name",
    *     required=true,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="lop_id",
    *     in="formData",
    *     description="Lop ID",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="recon",
    *     in="formData",
    *     description="Nilai Recon",
    *     required=false,
    *     type="integer"
    *   ),
     *   @SWG\Parameter(
    *     name="gr",
    *     in="formData",
    *     description="Nilai GR",
    *     required=false,
    *     type="integer"
    *   ),
    *   @SWG\Parameter(
    *     name="drm",
    *     in="formData",
    *     description="Nilai DRM",
    *     required=false,
    *     type="integer"
    *   ),
    *   @SWG\Parameter(
    *     name="region",
    *     in="formData",
    *     description="Region",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="witel",
    *     in="formData",
    *     description="Witel",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="datel",
    *     in="formData",
    *     description="Datel",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="sto",
    *     in="formData",
    *     description="Sto",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="reference_link",
    *     in="formData",
    *     description="Reference Link",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="type_project",
    *     in="formData",
    *     description="Type Project",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="key_correlation",
    *     in="formData",
    *     description="Key Correlation",
    *     required=false,
    *     type="string"
    *   ),
    *   @SWG\Parameter(
    *     name="odp_plan",
    *     in="formData",
    *     description="ODP Plan dalam bentuk array",
    *     required=false,
    _***      @SWG\Schema(
    *            type="array",
    *             items={
    *               "odp_name"="string"
    *            }
    *        )
    *   ),**_
    *   @SWG\Response(
    *     response=200,
    *     description="Input data oportunity"
    *   ),
    *   @SWG\Response(
    *     response=401,
    *     description="anda tidak memiliki izin"
    *   ),
    *   @SWG\Response(
    *     response="default",
    *     description="an ""unexpected"" error"
    *   )
    * )
    */

but it show error like this = 
@SWG\Parameter(name="odp_plan",in="formData")->type is required when @SWG\Parameter()->in == "formData" in \App\Htt
  p\Controllers\Oportunity->insert() in C:\job_huda\tomps\tomps-core/app\Http\Controllers\Oportunity.php on line 352

how to resolve it. thanks

**Comment by DarkaOnLine** [comment]
Please read Swagger documentation on how to annotate `formData`: https://swagger.io/docs/specification/2-0/describing-request-body/
