### ISSUE TITLE
Lumen 7 

### ISSUE THREAD

**Issue by fernandotugu** [DarkaOnLine/SwaggerLume#88]
Error: 
Required @OA\Info() not found

Proccess : 

uncomment this line (around line 26) in Create The Application section:
     $app->withFacades();
add this line before Register Container Bindings section:
     $app->configure('swagger-lume');
add this line in Register Service Providers section:
    $app->register(\SwaggerLume\ServiceProvider::class);

Execute
php artisan swagger-lume:publish-config -> ok

Execute
php artisan swagger-lume:publish-views -> Ok

Execute 
php artisan swagger-lume:generate -> Fail

Response:
Regenerating docs

In Logger.php line 39:
                                 
  Required @OA\Info() not found 

When i access api/documention, sometimes return blank page, sometimes return in log file :
2020-05-26 10:10:03] dev.ERROR: Required @OA\Info() not found {"http_request":"GET /api/documentation"

**Comment by DarkaOnLine** [comment]
As it says OA\Info not found. So you are missing required annotation :)

**Comment by itekk** [comment]
> 
> 
> As it says OA\Info not found. So you are missing required annotation :)

What is the fix here? I too get same error.
