### ISSUE TITLE
File Upload is not Working.

### ISSUE THREAD

**Issue by atapatel** [DarkaOnLine/SwaggerLume#9]
Hey I try to use parameter type as file but when i check at server side. i am not getting any one. :(

**Comment by DarkaOnLine** [comment]
Hi, 

Can you please be more specific? Where are you  uploading the file? What kind of file? Did you checked permissions?

**Comment by tranxuanhao2001** [comment]
I used to upload file, it is ok. You should check again 

> /**
     * @SWG\Post(path="/invoice/add-template",
     *      tags={"Invoices"},
     *      summary="Function create request to upload your custom invoice template",
     *      operationId="add-template",
     *      produces={"application/json"},
     *      consumes={"multipart/form-data"},
     *      @SWG\Parameter(
     *          description="Template file",
     *          in="formData",
     *          name="file",
     *          required=true,
     *          type="file",
     *      ),
     *      @SWG\Parameter(
     *          description="Template file name",
     *          in="formData",
     *          name="invoice_template_name",
     *          required=true,
     *          type="string",
     *      ),
     *      @SWG\Response(
     *          response="200",
     *          description="Successful operation",
     *          @SWG\Schema (
     *              @SWG\Property(
     *                  property="message",
     *                  type="string",
     *              ),
     *              @SWG\Property(
     *                  property="invoice_template_id",
     *                  type="string",
     *              ),
     *          )
     *      ),
     *      @SWG\Response(
     *          response="default",
     *          description="Error operation",
     *          @SWG\Schema(ref="#/definitions/Error")
     *      ),
     * )
     *
     * Create a new controller instance.
     *
     * @return void
     */

**Comment by atapatel** [comment]
Thanks it works now. please close this issue now.
