### ISSUE TITLE
asserts are not loading 

### ISSUE THREAD

**Issue by salinib** [DarkaOnLine/SwaggerLume#98]
i am using https for my website and i am getting blank page while opening swagger ui, looks like below is the issue
mixed Content: The page at 'https://xxxx/docs' was loaded over HTTPS, but requested an insecure script 'http://xxxx/swagger-ui-assets/swagger-ui-bundle.js?v=f87bee0fe2656c9fc64846775d5bffac'. This request has been blocked; the content must be served over HTTPS. please suggest the possible solution how can i load asserts with https

**Comment by mtracz** [comment]
Just setup trusted proxy via fideloper package and it will work.
https://github.com/fideloper/TrustedProxy

**Comment by sobernt** [comment]
@mtracz , it's no worked for me.

**Comment by rizkiazrial911** [comment]
@salinib https://github.com/DarkaOnLine/SwaggerLume/issues/53#issuecomment-489388919 maybe this helps you
